spring:
  config:
    import: classpath:secret.yml

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    kea.dpang.upload.feign.KakaoCloudObjectStorageClient: DEBUG